extraEnvVars:
  - name: KEYCLOAK_LOG_LEVEL
    value: DEBUG

persistence:
  enabled: true
  # existingClaim: keycloak-pvc

ingress:
  enabled: true
  hostname: keycloak.highpeaks.local
  ingressClassName: nginx
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/rewrite-target: /
  path: /
  pathType: Prefix
  tls: false

postgresql:
  enabled: true
  postgresqlUsername: keycloak
  postgresqlPassword: keycloakpassword
  postgresqlDatabase: keycloakdb

service:
  type: ClusterIP
  ports:
    http: 80
    https: 8443

proxy: edge   # Tells Keycloak traffic is HTTP internally, but TLS is terminated before Keycloak

auth:
  adminUser: keycloakadmin
  adminPassword: admin123

readinessProbe:
  httpGet:
    path: /realms/master
    port: http
  initialDelaySeconds: 60
  timeoutSeconds: 5

resources:
  requests:
    memory: "512Mi"
    cpu: "500m"
  limits:
    memory: "1Gi"
    cpu: "1"