# keycloak/values.yaml

keycloak:
  extraEnvVars:
    - name: KEYCLOAK_LOG_LEVEL
      value: DEBUG

  persistence:
    enabled: true
    # existingClaim: keycloak-pvc  # If you have a pre-created PVC, specify it here

  ingress:
    enabled: true
    hostname: keycloak.highpeaks.local
    annotations:
      kubernetes.io/ingress.class: "nginx"
      nginx.ingress.kubernetes.io/rewrite-target: /
    path: /
    tls: false


postgresql:
  enabled: true
  postgresqlUsername: keycloak
  postgresqlPassword: keycloakpassword
  postgresqlDatabase: keycloakdb

service:
  type: ClusterIP

readinessProbe:
  httpGet:
    path: /realms/master
    port: http
  initialDelaySeconds: 60
  timeoutSeconds: 5

resources:
  requests:
    memory: "512Mi"
    cpu: "500m"
  limits:
    memory: "1Gi"
    cpu: "1"
