name: CI

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build-and-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install Helm
        run: |
          curl -sSL https://get.helm.sh/helm-v3.11.0-linux-amd64.tar.gz -o helm.tar.gz
          tar -zxvf helm.tar.gz
          sudo mv linux-amd64/helm /usr/local/bin/helm

      - name: Install dependencies
        run: npm ci

      # Lint step (placeholder, ESLint could be added in the future)
      # - name: Run ESLint
      #   run: npm run lint

      - name: Validate Helm chart
        run: helm lint charts/highpeaks-identity

      - name: Build Docker image (CI test)
        run: docker build -t highpeaks-identity-service-ci:build .
